name = "zheng-xiubin-album"
main = "src/worker.js"
compatibility_date = "2023-12-01"

[[kv_namespaces]]
binding = "ALBUM_KV2"

[[r2_buckets]]
binding = "IMAGE_BUCKET"

[placement]
mode = "smart"

# 添加路由配置（如果需要自定义域名）
# [[routes]]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"
